# Build Configuration

name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build iOS (Development)
        run: eas build -p ios --profile development --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.INSPO }}